name: TPSigns
author: didjee2
version: 1.1.1
main: com.didjee2.TPSigns
commands:
     tpsign:
          aliases: [tpsigns]
          description: Info about the plugin / reload the plugin!
          usage: /<command>